# Generated by Django 3.2.8 on 2021-12-10 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_user_requested_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='unique',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='job',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
