# Generated by Django 4.0 on 2022-01-19 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_user_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='rank',
        ),
        migrations.AlterField(
            model_name='job',
            name='type',
            field=models.IntegerField(choices=[(1, 'Soldier'), (2, 'Miner'), (3, 'Builder'), (4, 'President')], default=1),
        ),
    ]
