# Generated by Django 3.2.8 on 2021-12-10 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20211210_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='rank',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='job',
            name='staff',
            field=models.BooleanField(default=False),
        ),
    ]
