# Generated by Django 3.2.8 on 2021-12-10 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20211210_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='job',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='website.job'),
            preserve_default=False,
        ),
    ]
