# Generated by Django 3.2.8 on 2021-12-11 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_alter_user_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='type',
            field=models.IntegerField(choices=[(1, 'Attacker'), (2, 'Defender'), (3, 'Builder'), (4, 'Emperor')], default=1),
        ),
    ]
