# Generated by Django 3.2.8 on 2021-12-12 02:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_auto_20211211_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('8f08efb8-76c5-42a5-8633-df050c7a40f6'), editable=False),
        ),
    ]
